name: test-watchdog-simple
base: core20 
version: '0.1'
summary: Test snapcraft systemd watchdog
description: |
  A test.

grade: devel
confinement: strict

apps:
  watchdog-no-notify:
    daemon: simple
    command: bin/daemon-no-notify
    plugs: [ daemon-notify ]
    watchdog-timeout: 6s 
    # if daemon does not notify systemd every six secs, systemd restarts it
    # this daemon does not notify so it IS restarted by the systemd watchdog

  watchdog-notify:
    daemon: simple
    command: bin/daemon-notify
    plugs: [ daemon-notify ]
    watchdog-timeout: 6s
    # if daemon does not notify systemd every six secs, systemd restarts it
    # this daemon does notify so it is not restarted by the systemd watchdog
    # but as a simple daemon it is then restarted after it completes

parts:
  daemon:
    source: .
    plugin: go
    build-packages: [ gcc ]
